GET http://localhost:3005

### list all

POST http://localhost:3005/auth/signup 
content-type: application/json

{
    "email": "test@test.com",
    "password": "admin123"
}

### find one

GET http://localhost:3005/auth/2

### find user by email

GET http://localhost:3005/auth?email=test@test.com

### delete one

DELETE http://localhost:3005/auth/1
