GET http://localhost:3005

### list all

POST http://localhost:3005/auth/signup 
content-type: application/json

{
    "email": "test02@test.com",
    "password": "admin123"
}

### find one

GET http://localhost:3005/auth/2

### find user by email

GET http://localhost:3005/auth?email=test@test.com

### delete user by id

DELETE http://localhost:3005/auth/4

### update user

PATCH http://localhost:3005/auth/2 
content-type: application/json

{
    "email": "te_ffst@testupdated.com",
    "password": "admin123_updated"
}

### update user BAD REQUEST

PATCH http://localhost:3005/auth/5 
content-type: application/json

{
    "email": "test@testmodified.com",
    "password": "admin123_modified"
}

### Find user  BAD REQUEST

GET http://localhost:3005/auth/3

### update user  BAD REQUEST

PATCH http://localhost:3005/auth/2 
content-type: application/json

{
    "email": "test@testmodified.com",
    "password": "admin123_modified"
}

### sign in

POST http://localhost:3005/auth/signin 
content-type: application/json

{
    "email": "test02@test.com",
    "password": "admin123"
}

### set the color

GET http://localhost:3005/auth/colors/red

### get the color

GET http://localhost:3005/auth/colors

### sign up

POST http://localhost:3005/auth/signup 
content-type: application/json

{
    "email": "test1111@test.com",
    "password": "admin123"
}

### Find user who am i

GET http://localhost:3005/auth/whoami

### sign out

POST http://localhost:3005/auth/signout


